### ISSUE TITLE
Build error while building the opencv library

### ISSUE THREAD

**Issue by vivekgalatage** [curtismuntz/third_party#1]
Hi,

I am trying to build the repository using:

```
bazel build //examples/opencv
```

But I am getting the below error:

```
DEBUG: Rule 'rules_foreign_cc' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "660c87215f49757396b6843cded65b85e6e05fb72acf6500f9366c7c50dde493"
DEBUG: Call stack for the definition of repository 'rules_foreign_cc' which is a http_archive (rule definition at /private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /Users/user/playground/third_party/WORKSPACE:9:1
DEBUG: Rule 'opencv_archive' indicated that a canonical reproducible form can be obtained by modifying arguments sha256 = "a35b00a71d77b484f73ec485c65fe56c7a6fa48acd5ce55c197aef2e13c78746"
DEBUG: Call stack for the definition of repository 'opencv_archive' which is a http_archive (rule definition at /private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/bazel_tools/tools/build_defs/repo/http.bzl:237:16):
 - /Users/user/playground/third_party/WORKSPACE:27:1
ERROR: /Users/user/playground/third_party/BUILD.bazel:19:1: in cmake_external rule //:dopencv:
Traceback (most recent call last):
  File "/Users/user/playground/third_party/BUILD.bazel", line 19
    cmake_external(name = 'dopencv')
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/cmake.bzl", line 47, in _cmake_external
    cc_external_rule_impl(ctx, attrs)
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 209, in cc_external_rule_impl
    _define_out_cc_info(ctx, attrs, inputs, outputs)
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/framework.bzl", line 645, in _define_out_cc_info
    create_linking_info(ctx, attrs.linkopts, outputs.librari...)
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 216, in create_linking_info
    cc_common.create_linking_context(user_link_flags = user_link_flag..., ...))
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 218, in cc_common.create_linking_context
    _create_libraries_to_link(ctx, files)
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 81, in _create_libraries_to_link
    _files_map((files.shared_libraries or []))
  File "/private/var/tmp/_bazel_user/83dc5f768b00f60c5fe3e0037c58d9dc/external/rules_foreign_cc/tools/build_defs/cc_toolchain_util.bzl", line 124, in _files_map
    fail("Can not have libraries with the...")
Can not have libraries with the same name in the same category
ERROR: Analysis of target '//examples/opencv' failed; build aborted: Analysis of target '//:dopencv' failed; build aborted
INFO: Elapsed time: 0.143s
INFO: 0 processes.
```

In this error log, there is a particular error which I am not able to understand:
`Can not have libraries with the same name in the same category`

I traced this error to https://github.com/bazelbuild/rules_foreign_cc/blob/6ad84f7739e47110eb4c48f7cdebbfd34e2f4f5f/tools/build_defs/cc_toolchain_util.bzl#L124

Any idea what is going wrong here?

I am using bazel version: **bazel 0.28.1-homebrew** on Mac OS 10.14.6

**Comment by vivekgalatage** [comment]
UPDATE:

The issue is inside the `_file_name_no_ext` inside cc_toolchain_util.bzl file of rules_foreign_cc repository.  The logic of partitioning the files names, results in the files with .so.3.4.4  to be the same ones.  Although the error message listed is misleading.

**Comment by curtismuntz** [comment]
Hey @vivekgalatage,

I've strayed away from this repo a while back in favor of using an explicit BUILD file to build opencv. My main repository that I'm trying to support is my "witness" project: https://github.com/curtismuntz/witness/blob/master/third_party/opencv.BUILD

Failing that, there's another great project out there that is doing what I was starting to do here (open source third party build files), but better: https://github.com/mjbots/bazel_deps

I haven't had any experience building either of these projects on mac so your results may vary.

**Comment by vivekgalatage** [comment]
Hey @curtismuntz, thank you for a quick response!  

Will definitely go through the references above which you mentioned.  I had a quick glance and those look really solid.  Let me give it a try.
